function grid = load_grid(cfg)
%IO.LOAD_GRID Load the target grid coordinates.
%
%   grid = io.load_grid(cfg)
%
%   Returns struct with fields: lon, lat, pres, time, year
%   Generated by ingest.read_moaa_temp_sal during the ingest step.

    grid = io.load_var(cfg, fullfile(cfg.paths.base_data, 'grid.mat'), 'grid');
end
