function fig15_timeseries_mlhb(cfg)
%FIG15_TIMESERIES_MLHB  Fig.15: Time series of ML heat budget terms.
%   Box average 210 E30°E, 40 E0°N with 13-month moving average.

    grid = load_grid(cfg);
    mlhb = load_var(cfg, 'mlhb');

    blon = 92:111;  blat = 61:70;  % 210 E30°E, 40 E0°N
    moveM = 13;

    series = struct( ...
        'data', { ...
            squeeze(mean(mlhb.dt.anom(blon,blat,:), [1 2], 'omitnan')), ...
            squeeze(mean(mlhb.asf.anom(blon,blat,:), [1 2], 'omitnan')), ...
            squeeze(mean(mlhb.adx.anom(blon,blat,:), [1 2], 'omitnan')), ...
            squeeze(mean(mlhb.ady.anom(blon,blat,:), [1 2], 'omitnan')), ...
            squeeze(mean(mlhb.entrain.anom(blon,blat,:), [1 2], 'omitnan')) ...
        }, ...
        'label', { ...
            'change rate of temperature', ...
            'surface heat flux', ...
            'zonal heat advection', ...
            'meridional heat advection', ...
            'entrainment' ...
        }, ...
        'style', {'k--','r-','m-','g-','b-'}, ...
        'width', {1, 1, 1, 1, 1} ...
    );

    [fig, ~] = plot_timeseries(grid.time, series, ...
        'ylim_range', [-0.5 0.5], ...
        'moving_avg', moveM, ...
        'tick_interval', 12, ...
        'fig_size', [1100 300], ...
        'legend_loc', 'southwest');

    outdir = fullfile(cfg.paths.data_root, cfg.paths.figures);
    save_fig(fig, 'fig15_timeseries_mlhb.png', 'output_dir', outdir);
end
