function fig15_timeseries_temp_budget_ml(cfg)
%FIG15_TIMESERIES_TEMP_BUDGET_ML Mixed-layer temperature budget time series.
%   Box average over 210-230 degrees E, 40-50 degrees N with a 13-month
%   moving average.

    grid = load_grid(cfg);
    temp_budget_ml = load_figure_var(cfg, 'temp_budget_ml');

    blon = 92:111;
    blat = 61:70;
    moveM = 13;

    series = struct( ...
        'data', { ...
            squeeze(mean(temp_budget_ml.tendency.anom( ...
                blon, blat, :), [1 2], 'omitnan')), ...
            squeeze(mean(temp_budget_ml.surface_forcing.anom( ...
                blon, blat, :), [1 2], 'omitnan')), ...
            squeeze(mean(temp_budget_ml.advection_zonal.anom( ...
                blon, blat, :), [1 2], 'omitnan')), ...
            squeeze(mean(temp_budget_ml.advection_meridional.anom( ...
                blon, blat, :), [1 2], 'omitnan')), ...
            squeeze(mean(temp_budget_ml.entrainment.anom( ...
                blon, blat, :), [1 2], 'omitnan')) ...
        }, ...
        'label', { ...
            'temperature tendency', ...
            'surface forcing', ...
            'zonal advection', ...
            'meridional advection', ...
            'entrainment' ...
        }, ...
        'style', {'k--', 'r-', 'm-', 'g-', 'b-'}, ...
        'width', {1, 1, 1, 1, 1});

    [fig, ~] = plot_timeseries(grid.time, series, ...
        'ylim_range', [-0.5 0.5], ...
        'moving_avg', moveM, ...
        'tick_interval', 12, ...
        'fig_size', [1100 300], ...
        'legend_loc', 'southwest');

    outdir = fullfile(cfg.paths.data_root, cfg.paths.figures);
    save_fig(fig, 'fig15_timeseries_temp_budget_ml.png', ...
        'output_dir', outdir);
end
