function run_figures(cfg)
%RUN_FIGURES  Generate all paper figures.
%
%   pipeline.run_figures(cfg)
%
%   Calls each fig## function in sequence. Each function loads its own
%   data via io.load_var and saves output to cfg.paths.figures.

    outdir = fullfile(cfg.paths.data_root, cfg.paths.figures);
    if ~isfolder(outdir)
        mkdir(outdir);
    end

    fprintf('=== Generating figures ===\n');

    fig_funcs = { ...
        @fig02_horizontal_anomaly, ...
        @fig03_hovmuller_isopycnal_temp, ...
        @fig04_hovmuller_isopycnal_temp2, ...
        @fig05_hovmuller_isopycnal_depth, ...
        @fig06_hovmuller_150m, ...
        @fig07_hovmuller_temp_3d, ...
        @fig08_hovmuller_depth_curl, ...
        @fig09_bplot_curl_depth, ...
        @fig10_correlation_map, ...
        @fig11_vertical_section_lon, ...
        @fig12_vertical_timesection, ...
        @fig13_depth_profile, ...
        @fig14_horizontal_mlhb, ...
        @fig15_timeseries_mlhb, ...
        @fig16_horizontal_flux_dh, ...
        @fig17_vertical_density, ...
        @fig18_trend_maps, ...
        @fig19_hovmuller_multi ...
    };

    for k = 1:numel(fig_funcs)
        name = func2str(fig_funcs{k});
        fprintf('  [%2d/%2d] %s ...', k, numel(fig_funcs), name);
        try
            fig_funcs{k}(cfg);
            fprintf(' done\n');
        catch ME
            fprintf(' ERROR: %s\n', ME.message);
        end
        close all;  % free memory between figures
    end

    fprintf('=== Figure generation complete ===\n');
end
