function stale = budget_output_is_stale(cfg, output_file, tracer_name)
%BUDGET_OUTPUT_IS_STALE Check data and code dependencies of a budget file.

    if ~ismember(tracer_name, {'temp', 'sal'})
        error('budget:InvalidTracer', ...
            'tracer_name must be ''temp'' or ''sal''.');
    end

    budget_dir = fileparts(mfilename('fullpath'));
    project_root = fileparts(fileparts(fileparts(budget_dir)));
    base = fullfile(cfg.paths.data_root, cfg.paths.base_data);
    analysis = fullfile(cfg.paths.data_root, cfg.paths.analysis);

    data_sources = { ...
        fullfile(base, [tracer_name '.mat']), ...
        fullfile(base, 'pden.mat'), ...
        fullfile(base, 'wind.mat'), ...
        fullfile(base, 'gvel.mat'), ...
        fullfile(analysis, 'mld.mat')};
    if strcmp(tracer_name, 'temp')
        data_sources{end + 1} = fullfile(base, 'flux.mat');
    else
        data_sources{end + 1} = fullfile(base, 'evap_precip.mat');
    end

    code_sources = { ...
        fullfile(project_root, 'config', 'create_config.m'), ...
        fullfile(project_root, 'src', 'analysis', 'basic', 'anomaly.m'), ...
        fullfile(project_root, 'src', 'analysis', 'basic', 'centered_monthly_change.m'), ...
        fullfile(project_root, 'src', 'analysis', 'basic', 'fixed_layer_mean.m'), ...
        fullfile(project_root, 'src', 'analysis', 'basic', 'mld_mean.m'), ...
        fullfile(project_root, 'src', 'analysis', 'basic', 'seconds_per_month.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'advection.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'air_sea_flux.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'compute_mld.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'compute_sal_budget.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'compute_temp_budget.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'compute_tracer_budget.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'entrain.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'finalize_tracer_budget.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'resolve_depth.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'salt_flux.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'temporal_tendency.m'), ...
        fullfile(project_root, 'src', 'analysis', 'budget', 'vertical_velocity.m')};

    stale = output_is_stale(output_file, [data_sources, code_sources]);
end
