function grid = load_grid(cfg)
%LOAD_GRID Load the target grid coordinates.
%
%   grid = load_grid(cfg)
%
%   Returns struct with fields: lon, lat, pres, time, year
%   Generated by read_moaa_temp_sal during the ingest step.

    grid = load_var(cfg, fullfile(cfg.paths.base_data, 'grid.mat'), 'grid');
end
